apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: getactions-app
  namespace: getactions
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: getactions-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70