apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: getactions
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: github-actions-token
  namespace: getactions
  annotations:
    kubernetes.io/service-account.name: github-actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-getactions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-actions
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: getactions