---
title: "fly.io"
description: "You only need a Dockerfile and this workflow ships your application to fly.io"
readme: |
  The deployment story of [fly.io](https://fly.io) is astonishing and with this workflow you can deploy your application to platform with ease. When your application was [initially setup](https://fly.io/docs/speedrun/) on fly.io, you can use this workflow to deploy your application whenever you pushed to the `main` branch.
secrets:
  FLY_API_TOKEN:
    description: "Your fly.io token which can be generated here: https://fly.io/user/personal_access_tokens"
---
name: "Deploy to fly.io"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Fly!
        run: flyctl deploy --remote-only --no-cache
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
