---
name: "Deploy to fly.io"
description: "Deploys your application to fly.io"
secrets:
  FLY_API_TOKEN:
    description: "Your fly.io token which can be generated here: https://fly.io/user/personal_access_tokens"
---
name: "Deploy to fly.io"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Fly!
        run: flyctl deploy --remote-only --no-cache
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
