name: "Deploy to fly.io"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Install dependencies
        run: bun i --frozen-lockfile
      
      - name: Populate latest workflows
        run: bun run populate-workflows

      - name: Fly!
        run: |
          flyctl deploy \
            --remote-only \
            --no-cache \
            --app ${{ secrets.PRODUCTION_FLY_APP_NAME }} \
            --access-token ${{ secrets.FLY_API_TOKEN }}
